//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace StarkBankExcel {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Main : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button login;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button2;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button3;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button transferOrder;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button getDictKey;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button Invoice;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button7;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button Help;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button1;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button8;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button9;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button10;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button11;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Main(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Planilha1", "Planilha1") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Main = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.login = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "19A5453E610F18142DA1BAA91D29A587ED2E11", "19A5453E610F18142DA1BAA91D29A587ED2E11", this, "login");
            this.button2 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "17053D61D1F15A1482019B2C1A4E6D57E3A971", "17053D61D1F15A1482019B2C1A4E6D57E3A971", this, "button2");
            this.button3 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1D1500907189BD14DA51B2181B162FBD75FE31", "1D1500907189BD14DA51B2181B162FBD75FE31", this, "button3");
            this.transferOrder = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1BD6BA4211BC3E14DAF185961A2B376D133421", "1BD6BA4211BC3E14DAF185961A2B376D133421", this, "transferOrder");
            this.getDictKey = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1CC3318201EE2A1421C19CEB15987574AED511", "1CC3318201EE2A1421C19CEB15987574AED511", this, "getDictKey");
            this.Invoice = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1DB344D2F14249140061BD5D11E614111405C1", "1DB344D2F14249140061BD5D11E614111405C1", this, "Invoice");
            this.button7 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1626B229C1652514446181B314A00A77AF6681", "1626B229C1652514446181B314A00A77AF6681", this, "button7");
            this.Help = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1F70BF05619C7F14D001A2031EA2288CEEF621", "1F70BF05619C7F14D001A2031EA2288CEEF621", this, "Help");
            this.button1 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1D58F8DCE161321493A19D8C10118F3363B411", "1D58F8DCE161321493A19D8C10118F3363B411", this, "button1");
            this.button8 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "10F831FB013D30140151820D1AB0BB140FD961", "10F831FB013D30140151820D1AB0BB140FD961", this, "button8");
            this.button9 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "28A34ED1D2633F2429D291182761C070389522", "28A34ED1D2633F2429D291182761C070389522", this, "button9");
            this.button10 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "23FDAD7A329F60245422A56B22EA1482F84402", "23FDAD7A329F60245422A56B22EA1482F84402", this, "button10");
            this.button11 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "2EF132486228D8243F428A6C298561D10E6622", "2EF132486228D8243F428A6C298561D10E6622", this, "button11");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // login
            // 
            this.login.BackColor = System.Drawing.SystemColors.Control;
            this.login.ForeColor = System.Drawing.SystemColors.ControlText;
            this.login.Name = "login";
            this.login.Text = "Acessar conta";
            this.login.UseVisualStyleBackColor = false;
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.SystemColors.Control;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Name = "button2";
            this.button2.Text = "Sair da conta";
            this.button2.UseVisualStyleBackColor = false;
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.SystemColors.Control;
            this.button3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button3.Name = "button3";
            this.button3.Text = "Consultar transferências";
            this.button3.UseVisualStyleBackColor = false;
            // 
            // transferOrder
            // 
            this.transferOrder.BackColor = System.Drawing.SystemColors.Control;
            this.transferOrder.ForeColor = System.Drawing.SystemColors.ControlText;
            this.transferOrder.Name = "transferOrder";
            this.transferOrder.Text = "Transferência com aprovaçâo";
            this.transferOrder.UseVisualStyleBackColor = false;
            // 
            // getDictKey
            // 
            this.getDictKey.BackColor = System.Drawing.SystemColors.Control;
            this.getDictKey.ForeColor = System.Drawing.SystemColors.ControlText;
            this.getDictKey.Name = "getDictKey";
            this.getDictKey.Text = "Consulta de Chave Pix";
            this.getDictKey.UseVisualStyleBackColor = false;
            // 
            // Invoice
            // 
            this.Invoice.BackColor = System.Drawing.SystemColors.Control;
            this.Invoice.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Invoice.Name = "Invoice";
            this.Invoice.Text = "Consulta de Invoices emitidas";
            this.Invoice.UseVisualStyleBackColor = false;
            // 
            // button7
            // 
            this.button7.BackColor = System.Drawing.SystemColors.Control;
            this.button7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button7.Name = "button7";
            this.button7.Text = "Emissâo de Invoice Pix";
            this.button7.UseVisualStyleBackColor = false;
            // 
            // Help
            // 
            this.Help.BackColor = System.Drawing.SystemColors.Control;
            this.Help.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Help.Name = "Help";
            this.Help.Text = "Ajuda";
            this.Help.UseVisualStyleBackColor = false;
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.SystemColors.Control;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Name = "button1";
            this.button1.Text = "Extrato";
            this.button1.UseVisualStyleBackColor = false;
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.SystemColors.Control;
            this.button8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button8.Name = "button8";
            this.button8.Text = "Consulta de Boletos Emitidos";
            this.button8.UseVisualStyleBackColor = false;
            // 
            // button9
            // 
            this.button9.BackColor = System.Drawing.SystemColors.Control;
            this.button9.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button9.Name = "button9";
            this.button9.Text = "Históricos de Boletos Emitidos";
            this.button9.UseVisualStyleBackColor = false;
            // 
            // button10
            // 
            this.button10.BackColor = System.Drawing.SystemColors.Control;
            this.button10.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button10.Name = "button10";
            this.button10.Text = "Consulta de Compras Realizadas";
            this.button10.UseVisualStyleBackColor = false;
            // 
            // button11
            // 
            this.button11.BackColor = System.Drawing.SystemColors.Control;
            this.button11.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button11.Name = "button11";
            this.button11.Text = "Extrato de Compras Realizadas";
            this.button11.UseVisualStyleBackColor = false;
            // 
            // Main
            // 
            this.login.BindingContext = this.BindingContext;
            this.button2.BindingContext = this.BindingContext;
            this.button3.BindingContext = this.BindingContext;
            this.transferOrder.BindingContext = this.BindingContext;
            this.getDictKey.BindingContext = this.BindingContext;
            this.Invoice.BindingContext = this.BindingContext;
            this.button7.BindingContext = this.BindingContext;
            this.Help.BindingContext = this.BindingContext;
            this.button1.BindingContext = this.BindingContext;
            this.button8.BindingContext = this.BindingContext;
            this.button9.BindingContext = this.BindingContext;
            this.button10.BindingContext = this.BindingContext;
            this.button11.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static Main _Main;
        
        internal static Main Main {
            get {
                return _Main;
            }
            set {
                if ((_Main == null)) {
                    _Main = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
